// ─────────────────────────────────────────────────────────────────────────────
// DAILY CHALLENGE
//
// Produces one deterministic puzzle per calendar day that is identical for
// every player.  All randomness derives from a seeded PRNG so there is no
// Math.random() call anywhere in this file.
//
// Seed derivation (transparent and reproducible):
//   1. Take today's ISO date string  e.g. "2025-03-15"
//   2. Append the salt             → "2025-03-15:daily-challenge"
//   3. Hash with djb2              → a 32-bit integer N
//   4. N seeds a mulberry32 PRNG   → deterministic float sequence
//   5. PRNG draws choose difficulty then 0-2 modifiers from a curated pool
//
// The puzzle board itself is generated by the existing generator using N as
// the board seed, so the board is also deterministic from the date.
//
// Modifier pool rules:
//   - Only modifiers that are fair at any difficulty are included
//   - time-out is excluded (unfair on extreme)
//   - Configurable modifiers use their defaultValue
//   - Incompatible pairs are never both selected (enforced by picking from a
//     filtered list after each selection)
// ─────────────────────────────────────────────────────────────────────────────

import { MODIFIER_MAP } from "./modifiers.js";
import { REGION_SETS, generateRandomRegionMap } from "./state.js";
import { PRNG } from "./generator.js";

// ── Curated modifier pool ─────────────────────────────────────────────────────
// Keys that are fair to apply to any randomly-chosen difficulty.
// time-out is excluded because a tight timer on extreme is unplayable.
const DAILY_MODIFIER_POOL = [
    "no-candidates",
    "blackout",
    "time-out",
    "candidate-only",
    "fragile",
    "living",
    "decaying",
    "ordered",
    "small-notepad",
    "symbols",
    "rainbow"
];

// Difficulty keys in ascending order — probability weights favour the middle
const DIFFICULTIES = ["veryeasy", "easy", "medium", "hard", "veryhard"];
// Weighted index table: veryeasy×1, easy×1, medium×2, hard×3, veryhard×2, extreme×1 (total 10)
const DIFFICULTY_WEIGHTS = [1, 1, 2, 3, 2, 1];

// ── Seeding ───────────────────────────────────────────────────────────────────

/** djb2 hash — fast, avalanche-free enough for a game seed */
function djb2(str) {
    let h = 5381;
    for (let i = 0; i < str.length; i++) {
        h = (Math.imul(h, 33) ^ str.charCodeAt(i)) >>> 0;
    }
    return h;
}

/** mulberry32 — a quality 32-bit PRNG seeded by a single integer */
function makePrng(seed) {
    let s = seed >>> 0;
    return function next() {
        s = (s + 0x6d2b79f5) >>> 0;
        let t = Math.imul(s ^ (s >>> 15), 1 | s);
        t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) >>> 0;
        return ((t ^ (t >>> 14)) >>> 0) / 0x100000000;
    };
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Returns a fully-formed meta object for today's Daily Challenge.
 * Pass an ISO date string (YYYY-MM-DD) to override "today" — useful for
 * testing or previewing tomorrow's puzzle.
 */
export function getDailyChallengeMeta(dateStr) {
    let date = dateStr;
    if (!date) {
        const d = new Date();
        date = [
            d.getFullYear(),
            String(d.getMonth() + 1).padStart(2, "0"),
            String(d.getDate()).padStart(2, "0")
        ].join("-");
    }
    const seed  = djb2(`${date}:daily-challenge`);
    const rand  = makePrng(seed);

    // ── Difficulty selection ──────────────────────────────────────────────────
    // Build a flat weighted table then pick from it
    const weightTable = [];
    for (let i = 0; i < DIFFICULTIES.length; i++) {
        for (let w = 0; w < DIFFICULTY_WEIGHTS[i]; w++) weightTable.push(i);
    }
    const diffIdx    = weightTable[Math.floor(rand() * weightTable.length)];
    const difficulty = DIFFICULTIES[diffIdx];

    // ── Modifier selection ────────────────────────────────────────────────────
    // 0 modifiers: 30 %   1 modifier: 50 %   2 modifiers: 20 %
    const modCountRoll = rand();
    const modCount = modCountRoll < 0.30 ? 0 : modCountRoll < 0.80 ? 1 : 2;

    const modifiers = {};
    let available   = [...DAILY_MODIFIER_POOL];

    for (let i = 0; i < modCount && available.length > 0; i++) {
        const pick = available[Math.floor(rand() * available.length)];
        const def  = MODIFIER_MAP[pick];
        if (!def) continue;

        modifiers[pick] = def.configurable ? { value: def.defaultValue } : true;

        // Remove the chosen key and any incompatible keys from future picks
        available = available.filter(
            k => k !== pick && !(def.incompatible ?? []).includes(k)
        );
    }

    // ── configurable modifier values ──────────────────────────────────────────
    // blackout: pick a reveal mode from its selectOptions
    if (modifiers["blackout"]) {
        const modes  = ["cell", "row", "col", "box"];
        const picked = modes[Math.floor(rand() * modes.length)];
        modifiers["blackout"] = { value: picked };
    }

    // ── Build label + description ─────────────────────────────────────────────
    const diffLabels = { veryeasy: "Very Easy", easy: "Easy", medium: "Medium", hard: "Hard", veryhard: "Very Hard" };

    // ── Region selection (Added V2) ───────────────────────────────────────────
    // 80% Classic, 20% Chaos
    const regionRoll = rand();
    let regionType = "classic";
    if (regionRoll > 0.80) regionType = "chaos";

    // Enforce incompatibility: Living is Classic-only
    if (regionType !== "classic" && modifiers["living"]) {
        delete modifiers["living"];
    }

    let regionMap = REGION_SETS[regionType];
    if (regionType === "chaos" || !regionMap) {
        regionMap = generateRandomRegionMap(new PRNG(seed));
    }

    const modKeys   = Object.keys(modifiers);
    const modLabels = modKeys.map(k => MODIFIER_MAP[k]?.label ?? k);

    const layoutLabel = {
        classic: "",
        chaos: "Chaos"
    }[regionType];

    const description = modKeys.length === 0
        ? `A clean ${layoutLabel ? layoutLabel + " " : ""}${diffLabels[difficulty].toLowerCase()} puzzle.`
        : `${layoutLabel ? layoutLabel + " · " : ""}${diffLabels[difficulty]} · ${modLabels.join(" + ")}`;

    return {
        type:             "daily-challenge",
        key:              date,                          // storage key per day
        label:            "Daily Challenge",
        difficulty,
        difficulty_label: diffLabels[difficulty],
        seed,                                            // board seed = date hash
        modifiers:        modKeys.length > 0 ? modifiers : null,
        description,
        date,
        regionType,
        regionMap
    };
}
